spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
    show_sql: true

  h2:
    console:
      enabled: true

  datasource:
    hikari.jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

  profiles:
    include: oauth

  session:
    store-type: jdbc